--- #YAML:1.0
name:                Catalyst-Plugin-Authentication-Credential-BBAuth
version:             0.02
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Catalyst:                      5.50
    Catalyst::Plugin::Authentication: 0
    Catalyst::Plugin::Session:     0
    Test::MockObject:              1.01
    Test::More:                    0
    UNIVERSAL::require:            0
    Yahoo::BBAuth:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jiro Nishiguchi <jiro@cpan.org>
